services:
  dca-phpinfo:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 2
    expose:
    - "8080"
    image: academiaonline/dca-phpinfo:1.0
version: "3.8"
